# Values for are-gateway.

# Enables debug mode
debug:
  enable: ${debug_enable}

istio:
  enable: ${istio_enable}

required:
  image: 
    repository: ${repository}
    %{ if strcontains(repository, "gematik1") }
    name: demis-are-gateway
    %{ endif }

# Image Pull Secrets
imagePullSecrets: 
  %{~ for pull_secret in image_pull_secrets ~}
  - name: ${pull_secret}
  %{~ endfor ~}

config:
  files: {}

# Extra Environment Variables to be defined
# customEnvVars
#   key: value
customEnvVars:
  # Prevents empty values that can delete the default environment variables
  TERRAFORM_DEPLOYMENT: true
  GATEWAY_SERVER_PORT: "8080"
  ANPS_BASE_URL: "http://are-notification-processing-service.${namespace}.svc.cluster.local"
  ANPS_SENDER: "are-gateway"
  ANPS_SURVEILLANCE_PATH: "/$process-are-notification"
  %{~ for flag_name, flag_value in feature_flags ~}
  ${flag_name} : ${flag_value}
  %{~ endfor ~}
  %{~ for config_name, config_value in config_options ~}
  ${config_name} : "${config_value}"
  %{~ endfor ~}
  
%{~ if feature_flag_new_istio_sidecar_requests_and_limits && istio_proxy_resources != null ~}
podAnnotations:
  sidecar.istio.io/proxyCPU: ${istio_proxy_resources.requests.cpu}
  sidecar.istio.io/proxyMemory: ${istio_proxy_resources.requests.memory}
  sidecar.istio.io/proxyMemoryLimit: ${istio_proxy_resources.limits.memory}
%{endif}

%{~ if replica_count != null ~}
# Number of Pod Replicas desired
replicaCount: ${replica_count}
%{endif}

%{~ if resource_block != null ~}
# Override Resource Definitions for Pod
${resource_block}
%{endif}
