# Values for the are-notification-processing-service Helm Template
# Enables debug mode
debug:
  enable: ${debug_enable}

istio:
  enable: ${istio_enable}

required:
  image:
    repository: ${repository}
    %{ if strcontains(repository, "gematik1") }
    name: demis-are-notification-processing-service
    %{ endif }

# Image Pull Secrets
imagePullSecrets:
  %{~ for pull_secret in image_pull_secrets ~}
  - name: ${pull_secret}
  %{~ endfor ~}

customEnvVars:
  # Prevents empty values that can delete the default environment variables
  TERRAFORM_DEPLOYMENT: true
  SERVER_PORT: "8080"
  REDIS_USER: "${redis_user}"
  REDIS_HOST: "redis-cus.idm.svc.cluster.local"
  REDIS_PORT: "6379"
  SERVLET_CONTEXT_PATH: "/"
  VALIDATION_SERVICE_URL: "http://validation-service.${namespace}.svc.cluster.local"
  ENRICHMENT_SERVICE_URL: "http://context-enrichment-service.demis.svc.cluster.local"
  FHIR_STORAGE_SERVICE_URL: "http://fhir-storage-writer.demis.svc.cluster.local"
  FHIR_STORAGE_CONTEXT_PATH: "/"
  %{~ for flag_name, flag_value in feature_flags ~}
  ${flag_name} : ${flag_value}
  %{~ endfor ~}
  %{~ for config_name, config_value in config_options ~}
  ${config_name} : "${config_value}"
  %{~ endfor ~}

%{~ if feature_flag_new_istio_sidecar_requests_and_limits && istio_proxy_resources != null ~}
podAnnotations:
  checksum/redis_reader: "${redis_cus_reader_credentials_checksum}"
  sidecar.istio.io/proxyCPU: ${istio_proxy_resources.requests.cpu}
  sidecar.istio.io/proxyMemory: ${istio_proxy_resources.requests.memory}
  sidecar.istio.io/proxyMemoryLimit: ${istio_proxy_resources.limits.memory}
%{endif}

%{~ if replica_count != null ~}
# Number of Pod Replicas desired
replicaCount: ${replica_count}
%{endif}

%{~ if resource_block != null ~}
# Override Resource Definitions for Pod
${resource_block}
%{endif}