peerAuthenticationRules:
  enabled: true
  # Controlling the Postgres Peer Authentication. Needs to be disabled in the Terraform environments
  peerAuthenticationPostgres:
    enabled: false
  # Controlling the PgBouncer Peer Authentication. Needs to be disabled in the Terraform environments
  peerAuthenticationPgBouncer:
    enabled: false

demis:
  enabled: false

dmz:
  enabled: false

idm:
  enabled: false

mesh:
  enabled: false