restrict_image_registries:
  enabled: true
  image_registries:
    - ${repository}/*
    - docker.io/istio/*
  
verify_image_signature:
  enabled: true
  image_registries:
    - ${repository}/*
  image_pull_secrets:
    ${indent (4, yamlencode(image_pull_secrets))}